name: Run Black on PR
inputs:
    access-token:
      description: "GitHub access token"
      required: true
    path:
      description: "Directory to run Black on"
      required: true
      default: .
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.access-token }}
    - ${{ inputs.path }}

