name: Run Prettier on PR
inputs:
  access-token:
    description: "GitHub access token"
    required: true
  path:
    description: "Directory to run Prettier on"
    required: true
    default: .
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.access-token }}
    - ${{ inputs.path }}
